### ISSUE TITLE
SPIKE: Investigate CICD process for backend and Create Documentation

### ISSUE THREAD

**Issue by Riyanat** [turntabl/Tahoot#31]
Outcome: Research the CICD process  that is currently used to deploy the application and understand how branches are being deployed to Heroku. 

By the end of this issue, Do an informal presentation to the rest of the team on your findings and add the information to a document and share it with the team

Additional Notes
- Speak to Patricia who will have more information
- Identify which Heroku account the applications are being deployed to.

**Comment by dennismachu** [comment]
Assumptions:
CI/CD: Travis CI
Server: AWS EC2 (Given that Heroku is down)

**Comment by dennismachu** [comment]
Here is documentation on the CI/CD
[ https://docs.google.com/presentation/d/1Czri1jXkc0_8AcrDvT4CLZ8uCeat7Nz_vsv0Mwrx5mg/edit?usp=sharing ]
